"""Generate responsive contributor cards and embed them in the profile README."""

from pathlib import Path, PurePosixPath
from urllib.parse import urlparse
from urllib.request import Request, urlopen
import base64
import hashlib
import html
import mimetypes
import random
import re
import sys
import unicodedata

import yaml


# Repository paths and README markers used by the renderer.
ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "contributors.yml"
README_FILE = ROOT / "profile" / "README.md"
CARD_DIR = ROOT / "images" / "contributor-cards"
CARD_README_DIR = PurePosixPath("..", "images", "contributor-cards")
START_MARKER = "<!-- contributors:start -->"
END_MARKER = "<!-- contributors:end -->"
GENERATED_MARKER = "<!-- Generated by scripts/render_contributors.py. -->"
TEXT_ENCODING = "utf-8"
OUTPUT_NEWLINE = "\n"

# Supported contributor fields and validation rules.
CONTRIBUTORS_KEY = "contributors"
NAME_FIELD = "name"
GITHUB_FIELD = "github"
URL_FIELD = "url"
AVATAR_FIELD = "avatar"
ALLOWED_FIELDS = {NAME_FIELD, GITHUB_FIELD, URL_FIELD, AVATAR_FIELD}
OPTIONAL_FIELDS = ALLOWED_FIELDS - {NAME_FIELD}
URL_FIELDS = (URL_FIELD, AVATAR_FIELD)
GITHUB_USERNAME = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$")
WEB_SCHEMES = frozenset({"http", "https"})

# Remote avatar download settings.
GITHUB_BASE_URL = "https://github.com"
GITHUB_AVATAR_SIZE = 192
DOWNLOAD_TIMEOUT_SECONDS = 20
DOWNLOAD_USER_AGENT = "OpenEDM-contributor-renderer"
MAX_AVATAR_MIB = 5
BYTES_PER_MIB = 1024 * 1024
MAX_AVATAR_BYTES = MAX_AVATAR_MIB * BYTES_PER_MIB

# Stable generated filename settings.
CARD_FILE_SUFFIX = ".svg"
FILENAME_HASH_LENGTH = 8
FALLBACK_FILENAME_SLUG = "contributor"

# System-backed randomizer used to give contributors an unbiased display order.
CONTRIBUTOR_ORDER_RANDOMIZER = random.SystemRandom()

# SVG card geometry. Derived values keep the avatar and border centered.
CARD_WIDTH = 160
CARD_HEIGHT = 144
CARD_MARGIN = 4
CARD_STROKE_WIDTH = 1
CARD_CORNER_RADIUS = 10
CARD_RECT_X = CARD_MARGIN + CARD_STROKE_WIDTH / 2
CARD_RECT_Y = CARD_RECT_X
CARD_RECT_WIDTH = CARD_WIDTH - 2 * CARD_RECT_X
CARD_RECT_HEIGHT = CARD_HEIGHT - 2 * CARD_RECT_Y
AVATAR_CENTER_X = CARD_WIDTH // 2
AVATAR_CENTER_Y = 57
AVATAR_RADIUS = 42
AVATAR_BORDER_RADIUS = 44
AVATAR_SIZE = AVATAR_RADIUS * 2
AVATAR_X = AVATAR_CENTER_X - AVATAR_RADIUS
AVATAR_Y = AVATAR_CENTER_Y - AVATAR_RADIUS
NAME_BASELINE_Y = 123

# Typography settings for contributor names.
LONG_NAME_THRESHOLD = 16
DEFAULT_FONT_SIZE = 14
LONG_NAME_FONT_SIZE = 12
FONT_WEIGHT = 600
FONT_FAMILY = '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif'

# GitHub-inspired colors for light and dark display modes.
CARD_BACKGROUND = "none"
LIGHT_AVATAR_BACKGROUND = "#ffffff"
LIGHT_BORDER_COLOR = "#d0d7de"
LIGHT_TEXT_COLOR = "#1f2328"
DARK_AVATAR_BACKGROUND = "#0d1117"
DARK_BORDER_COLOR = "#30363d"
DARK_TEXT_COLOR = "#f0f6fc"

# File signatures used when an HTTP server supplies an inaccurate MIME type.
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
JPEG_SIGNATURE = b"\xff\xd8\xff"
GIF_SIGNATURES = (b"GIF87a", b"GIF89a")
WEBP_CONTAINER_SIGNATURE = b"RIFF"
WEBP_FORMAT_SIGNATURE = b"WEBP"
SVG_OPENING_TAG = b"<svg"


def is_web_url(value):
    """Return whether a value is an absolute HTTP or HTTPS URL."""
    parsed = urlparse(value)
    return parsed.scheme in WEB_SCHEMES and bool(parsed.netloc)


def load_contributors():
    """Load and validate contributor records from the YAML data file."""
    data = yaml.safe_load(DATA_FILE.read_text(encoding=TEXT_ENCODING)) or {}
    contributors = data.get(CONTRIBUTORS_KEY)
    if not isinstance(contributors, list):
        raise ValueError(f'"{CONTRIBUTORS_KEY}" must be a list')

    for index, person in enumerate(contributors, start=1):
        if not isinstance(person, dict):
            raise ValueError(f"Contributor {index} must be an object")

        unknown = set(person) - ALLOWED_FIELDS
        if unknown:
            raise ValueError(
                f"Contributor {index} has unknown fields: {', '.join(sorted(unknown))}"
            )

        if (
            not isinstance(person.get(NAME_FIELD), str)
            or not person[NAME_FIELD].strip()
        ):
            raise ValueError(
                f'Contributor {index} must have a non-empty "{NAME_FIELD}"'
            )

        for field in OPTIONAL_FIELDS:
            value = person.get(field)
            if value is not None and (not isinstance(value, str) or not value.strip()):
                raise ValueError(f'Contributor {index} has an invalid "{field}"')

        github = person.get(GITHUB_FIELD)
        if github and not GITHUB_USERNAME.fullmatch(github):
            raise ValueError(f'Contributor {index} has an invalid GitHub username')
        if not github and not person.get(URL_FIELD):
            raise ValueError(
                f'Contributor {index} must have either "{GITHUB_FIELD}" or '
                f'"{URL_FIELD}"'
            )
        if not github and not person.get(AVATAR_FIELD):
            raise ValueError(
                f'Contributor {index} without GitHub must have an "{AVATAR_FIELD}"'
            )

        for field in URL_FIELDS:
            value = person.get(field)
            if value and "://" in value and not is_web_url(value):
                raise ValueError(f'Contributor {index} has an invalid "{field}" URL')

    return contributors


def avatar_source(person):
    """Resolve a contributor avatar to either a remote URL or a local path."""
    avatar = person.get(AVATAR_FIELD)
    if not avatar:
        return (
            f'{GITHUB_BASE_URL}/{person[GITHUB_FIELD]}.png?size={GITHUB_AVATAR_SIZE}'
        )

    if is_web_url(avatar):
        return avatar

    path = PurePosixPath(avatar)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f'Invalid local avatar path: "{avatar}"')
    local_path = ROOT / Path(*path.parts)
    if not local_path.is_file():
        raise ValueError(f'Local avatar does not exist: "{avatar}"')
    return local_path


def detect_image_type(content, hint=None):
    """Detect the avatar MIME type from its bytes, falling back to a MIME hint."""
    if content.startswith(PNG_SIGNATURE):
        return "image/png"
    if content.startswith(JPEG_SIGNATURE):
        return "image/jpeg"
    if content.startswith(GIF_SIGNATURES):
        return "image/gif"
    if (
        content.startswith(WEBP_CONTAINER_SIGNATURE)
        and content[8:12] == WEBP_FORMAT_SIGNATURE
    ):
        return "image/webp"
    if content.lstrip().startswith(SVG_OPENING_TAG):
        return "image/svg+xml"
    if hint and hint.startswith("image/"):
        return hint
    raise ValueError("Avatar is not a supported image")


def avatar_data_uri(person):
    """Read or download an avatar and return a self-contained base64 data URI."""
    source = avatar_source(person)
    if isinstance(source, Path):
        content = source.read_bytes()
        mime_hint = mimetypes.guess_type(source.name)[0]
    else:
        request = Request(source, headers={"User-Agent": DOWNLOAD_USER_AGENT})
        with urlopen(request, timeout=DOWNLOAD_TIMEOUT_SECONDS) as response:
            content = response.read(MAX_AVATAR_BYTES + 1)
            mime_hint = response.headers.get_content_type()

    if len(content) > MAX_AVATAR_BYTES:
        raise ValueError(f'Avatar is larger than {MAX_AVATAR_MIB} MiB: "{source}"')
    mime = detect_image_type(content, mime_hint)
    encoded = base64.b64encode(content).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def card_filename(person):
    """Build a stable, filesystem-safe SVG filename for a contributor."""
    identity = person.get(GITHUB_FIELD) or (
        f'{person[NAME_FIELD]}-{person.get(URL_FIELD, "")}'
    )
    ascii_name = unicodedata.normalize("NFKD", identity).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_name.lower()).strip("-")
    if not slug:
        slug = FALLBACK_FILENAME_SLUG
    digest = hashlib.sha256(identity.encode(TEXT_ENCODING)).hexdigest()[
        :FILENAME_HASH_LENGTH
    ]
    return f"{slug}-{digest}{CARD_FILE_SUFFIX}"


def render_card(person):
    """Render one contributor as a self-contained, theme-aware SVG card."""
    name = html.escape(person[NAME_FIELD].strip(), quote=True)
    avatar = avatar_data_uri(person)
    font_size = (
        DEFAULT_FONT_SIZE
        if len(person[NAME_FIELD].strip()) <= LONG_NAME_THRESHOLD
        else LONG_NAME_FONT_SIZE
    )
    return f'''{GENERATED_MARKER}
<svg xmlns="http://www.w3.org/2000/svg" width="{CARD_WIDTH}" height="{CARD_HEIGHT}" viewBox="0 0 {CARD_WIDTH} {CARD_HEIGHT}" role="img" aria-labelledby="title">
  <title id="title">{name}</title>
  <style>
    .card {{ fill: {CARD_BACKGROUND}; stroke: {LIGHT_BORDER_COLOR}; }}
    .avatar-border {{ fill: {LIGHT_AVATAR_BACKGROUND}; stroke: {LIGHT_BORDER_COLOR}; }}
    .name {{ fill: {LIGHT_TEXT_COLOR}; font: {FONT_WEIGHT} {font_size}px {FONT_FAMILY}; }}
    @media (prefers-color-scheme: dark) {{
      .card {{ fill: {CARD_BACKGROUND}; stroke: {DARK_BORDER_COLOR}; }}
      .avatar-border {{ fill: {DARK_AVATAR_BACKGROUND}; stroke: {DARK_BORDER_COLOR}; }}
      .name {{ fill: {DARK_TEXT_COLOR}; }}
    }}
  </style>
  <rect class="card" x="{CARD_RECT_X:g}" y="{CARD_RECT_Y:g}" width="{CARD_RECT_WIDTH:g}" height="{CARD_RECT_HEIGHT:g}" rx="{CARD_CORNER_RADIUS}"/>
  <circle class="avatar-border" cx="{AVATAR_CENTER_X}" cy="{AVATAR_CENTER_Y}" r="{AVATAR_BORDER_RADIUS}"/>
  <clipPath id="avatar-clip"><circle cx="{AVATAR_CENTER_X}" cy="{AVATAR_CENTER_Y}" r="{AVATAR_RADIUS}"/></clipPath>
  <image href="{avatar}" x="{AVATAR_X}" y="{AVATAR_Y}" width="{AVATAR_SIZE}" height="{AVATAR_SIZE}" preserveAspectRatio="xMidYMid slice" clip-path="url(#avatar-clip)"/>
  <text class="name" x="{AVATAR_CENTER_X}" y="{NAME_BASELINE_Y}" text-anchor="middle">{name}</text>
</svg>
'''


def contributor_url(person):
    """Return the destination opened when a contributor card is clicked."""
    if person.get(GITHUB_FIELD):
        return f'{GITHUB_BASE_URL}/{person[GITHUB_FIELD]}'
    return person[URL_FIELD]


def randomize_contributor_order(contributors):
    """Return a shuffled copy without changing the order in the YAML data."""
    randomized = list(contributors)
    CONTRIBUTOR_ORDER_RANDOMIZER.shuffle(randomized)
    return randomized


def render_cards(contributors):
    """Generate all SVG cards and return randomly ordered README markup."""
    if not contributors:
        return "<!-- No contributors listed yet. -->"

    CARD_DIR.mkdir(parents=True, exist_ok=True)
    expected = set()
    cards = []
    items = []
    for person in randomize_contributor_order(contributors):
        filename = card_filename(person)
        if filename in expected:
            raise ValueError(f'Duplicate contributor: "{person[NAME_FIELD]}"')
        expected.add(filename)
        cards.append((filename, render_card(person)))

        name = html.escape(person[NAME_FIELD].strip(), quote=True)
        link = html.escape(contributor_url(person), quote=True)
        image = f"{CARD_README_DIR.as_posix()}/{filename}"
        items.append(
            f'<a href="{link}"><img src="{image}" width="{CARD_WIDTH}" '
            f'height="{CARD_HEIGHT}" '
            f'alt="{name}"></a>'
        )

    for filename, card in cards:
        (CARD_DIR / filename).write_text(
            card, encoding=TEXT_ENCODING, newline=OUTPUT_NEWLINE
        )

    for old_card in CARD_DIR.glob(f"*{CARD_FILE_SUFFIX}"):
        if old_card.name not in expected:
            prefix = old_card.read_text(encoding=TEXT_ENCODING)[: len(GENERATED_MARKER)]
            if prefix == GENERATED_MARKER:
                old_card.unlink()

    return "<p>\n" + "\n".join(items) + "\n</p>"


def main():
    """Regenerate contributor cards and replace the marked README section."""
    readme = README_FILE.read_text(encoding=TEXT_ENCODING)
    if readme.count(START_MARKER) != 1 or readme.count(END_MARKER) != 1:
        raise ValueError("README must contain exactly one pair of contributor markers")

    before, remainder = readme.split(START_MARKER, 1)
    _, after = remainder.split(END_MARKER, 1)
    generated = render_cards(load_contributors())
    updated = f"{before}{START_MARKER}\n\n{generated}\n\n{END_MARKER}{after}"
    README_FILE.write_text(
        updated, encoding=TEXT_ENCODING, newline=OUTPUT_NEWLINE
    )
    print(f"Updated {README_FILE.relative_to(ROOT)} and contributor cards")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
